
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "S2C_common.h"
namespace Game {
namespace Network {
namespace S2C {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_SendTest,
               
		Rmi_NotifyJoinPlayer,
               
		Rmi_GivePlayerItem,
	};

	int g_RmiIDListCount = 3;

}
}
}


