 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
            
using Nettention.Proud; 
namespace Game.Network.C2S
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID SendTest = (Nettention.Proud.RmiID)2000+1;
			public const Nettention.Proud.RmiID SendTest2 = (Nettention.Proud.RmiID)2000+2;
			public const Nettention.Proud.RmiID ReqJoinGame = (Nettention.Proud.RmiID)2000+3;
			public const Nettention.Proud.RmiID ReqMove = (Nettention.Proud.RmiID)2000+4;
			public const Nettention.Proud.RmiID ReqUseItem = (Nettention.Proud.RmiID)2000+5;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			SendTest,
			SendTest2,
			ReqJoinGame,
			ReqMove,
			ReqUseItem,
		};
	}
}

				 
