




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;	     

            
using Nettention.Proud; 
namespace Game.Network.C2S
{
	public class Stub:Nettention.Proud.RmiStub
	{
public AfterRmiInvocationDelegate AfterRmiInvocation = delegate(Nettention.Proud.AfterRmiSummary summary) {};
public BeforeRmiInvocationDelegate BeforeRmiInvocation = delegate(Nettention.Proud.BeforeRmiSummary summary) {};

		public delegate bool SendTestDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string value);  
		public SendTestDelegate SendTest = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string value)
		{ 
			return false;
		};
		public delegate bool SendTest2Delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, UnityEngine.Vector3 value);  
		public SendTest2Delegate SendTest2 = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, UnityEngine.Vector3 value)
		{ 
			return false;
		};
		public delegate bool ReqJoinGameDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext);  
		public ReqJoinGameDelegate ReqJoinGame = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext)
		{ 
			return false;
		};
		public delegate bool ReqMoveDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int entityId, UnityEngine.Vector3 position, UnityEngine.Vector3 vel);  
		public ReqMoveDelegate ReqMove = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int entityId, UnityEngine.Vector3 position, UnityEngine.Vector3 vel)
		{ 
			return false;
		};
		public delegate bool ReqUseItemDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int playerEID, int targetEntityId, int itemEntityId);  
		public ReqUseItemDelegate ReqUseItem = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int playerEID, int targetEntityId, int itemEntityId)
		{ 
			return false;
		};
	public override bool ProcessReceivedMessage(Nettention.Proud.ReceivedMessage pa, Object hostTag) 
	{
		Nettention.Proud.HostID remote=pa.RemoteHostID;
		if(remote==Nettention.Proud.HostID.HostID_None)
		{
			ShowUnknownHostIDWarning(remote);
		}

		Nettention.Proud.Message __msg=pa.ReadOnlyMessage;
		int orgReadOffset = __msg.ReadOffset;
        Nettention.Proud.RmiID __rmiID = Nettention.Proud.RmiID.RmiID_None;
        if (!__msg.Read( out __rmiID))
            goto __fail;
					
		switch(__rmiID)
		{
        case Common.SendTest:
            ProcessReceivedMessage_SendTest(__msg, pa, hostTag, remote);
            break;
        case Common.SendTest2:
            ProcessReceivedMessage_SendTest2(__msg, pa, hostTag, remote);
            break;
        case Common.ReqJoinGame:
            ProcessReceivedMessage_ReqJoinGame(__msg, pa, hostTag, remote);
            break;
        case Common.ReqMove:
            ProcessReceivedMessage_ReqMove(__msg, pa, hostTag, remote);
            break;
        case Common.ReqUseItem:
            ProcessReceivedMessage_ReqUseItem(__msg, pa, hostTag, remote);
            break;
		default:
			 goto __fail;
		}
		return true;
__fail:
	  {
			__msg.ReadOffset = orgReadOffset;
			return false;
	  }
	}
    void ProcessReceivedMessage_SendTest(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        string value; MyMarshaler.Read(__msg,out value);	
core.PostCheckReadMessage(__msg, RmiName_SendTest);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=value.ToString()+",";
        NotifyCallFromStub(Common.SendTest, RmiName_SendTest,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.SendTest;
        summary.rmiName = RmiName_SendTest;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =SendTest (remote,ctx , value );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_SendTest);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.SendTest;
        summary.rmiName = RmiName_SendTest;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_SendTest2(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        UnityEngine.Vector3 value; MyMarshaler.Read(__msg,out value);	
core.PostCheckReadMessage(__msg, RmiName_SendTest2);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=value.ToString()+",";
        NotifyCallFromStub(Common.SendTest2, RmiName_SendTest2,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.SendTest2;
        summary.rmiName = RmiName_SendTest2;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =SendTest2 (remote,ctx , value );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_SendTest2);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.SendTest2;
        summary.rmiName = RmiName_SendTest2;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_ReqJoinGame(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        core.PostCheckReadMessage(__msg, RmiName_ReqJoinGame);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
                NotifyCallFromStub(Common.ReqJoinGame, RmiName_ReqJoinGame,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.ReqJoinGame;
        summary.rmiName = RmiName_ReqJoinGame;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =ReqJoinGame (remote,ctx  );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_ReqJoinGame);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.ReqJoinGame;
        summary.rmiName = RmiName_ReqJoinGame;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_ReqMove(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int entityId; MyMarshaler.Read(__msg,out entityId);	
UnityEngine.Vector3 position; MyMarshaler.Read(__msg,out position);	
UnityEngine.Vector3 vel; MyMarshaler.Read(__msg,out vel);	
core.PostCheckReadMessage(__msg, RmiName_ReqMove);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=entityId.ToString()+",";
parameterString+=position.ToString()+",";
parameterString+=vel.ToString()+",";
        NotifyCallFromStub(Common.ReqMove, RmiName_ReqMove,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.ReqMove;
        summary.rmiName = RmiName_ReqMove;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =ReqMove (remote,ctx , entityId, position, vel );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_ReqMove);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.ReqMove;
        summary.rmiName = RmiName_ReqMove;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_ReqUseItem(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int playerEID; MyMarshaler.Read(__msg,out playerEID);	
int targetEntityId; MyMarshaler.Read(__msg,out targetEntityId);	
int itemEntityId; MyMarshaler.Read(__msg,out itemEntityId);	
core.PostCheckReadMessage(__msg, RmiName_ReqUseItem);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=playerEID.ToString()+",";
parameterString+=targetEntityId.ToString()+",";
parameterString+=itemEntityId.ToString()+",";
        NotifyCallFromStub(Common.ReqUseItem, RmiName_ReqUseItem,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.ReqUseItem;
        summary.rmiName = RmiName_ReqUseItem;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =ReqUseItem (remote,ctx , playerEID, targetEntityId, itemEntityId );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_ReqUseItem);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.ReqUseItem;
        summary.rmiName = RmiName_ReqUseItem;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_SendTest="SendTest";
public const string RmiName_SendTest2="SendTest2";
public const string RmiName_ReqJoinGame="ReqJoinGame";
public const string RmiName_ReqMove="ReqMove";
public const string RmiName_ReqUseItem="ReqUseItem";
       
public const string RmiName_First = RmiName_SendTest;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_SendTest="";
public const string RmiName_SendTest2="";
public const string RmiName_ReqJoinGame="";
public const string RmiName_ReqMove="";
public const string RmiName_ReqUseItem="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList { get{return Common.RmiIDList;} }
		
	}
}

