 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
            
using Nettention.Proud; 
namespace Game.Network.S2C
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID SendTest = (Nettention.Proud.RmiID)3000+1;
			public const Nettention.Proud.RmiID NotifyJoinPlayer = (Nettention.Proud.RmiID)3000+2;
			public const Nettention.Proud.RmiID GivePlayerItem = (Nettention.Proud.RmiID)3000+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			SendTest,
			NotifyJoinPlayer,
			GivePlayerItem,
		};
	}
}

				 
