




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;	     

            
using Nettention.Proud; 
            
using System.Collections.Generic; 
namespace Game.Network.S2C
{
	public class Stub:Nettention.Proud.RmiStub
	{
public AfterRmiInvocationDelegate AfterRmiInvocation = delegate(Nettention.Proud.AfterRmiSummary summary) {};
public BeforeRmiInvocationDelegate BeforeRmiInvocation = delegate(Nettention.Proud.BeforeRmiSummary summary) {};

		public delegate bool SendTestDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string value);  
		public SendTestDelegate SendTest = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string value)
		{ 
			return false;
		};
		public delegate bool NotifyJoinPlayerDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, GameServer.Struct.NEntityList joinedPlayers);  
		public NotifyJoinPlayerDelegate NotifyJoinPlayer = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, GameServer.Struct.NEntityList joinedPlayers)
		{ 
			return false;
		};
		public delegate bool NotifyLeavePlayeRDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int playerHostId);  
		public NotifyLeavePlayeRDelegate NotifyLeavePlayeR = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int playerHostId)
		{ 
			return false;
		};
		public delegate bool NotifyServerMessageDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string msg);  
		public NotifyServerMessageDelegate NotifyServerMessage = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string msg)
		{ 
			return false;
		};
		public delegate bool NotifyItemCreateDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int id, int itemIndex, UnityEngine.Vector3 createdPosition);  
		public NotifyItemCreateDelegate NotifyItemCreate = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int id, int itemIndex, UnityEngine.Vector3 createdPosition)
		{ 
			return false;
		};
		public delegate bool NotifyEntityMoveDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int id, UnityEngine.Vector3 position, UnityEngine.Vector3 vel);  
		public NotifyEntityMoveDelegate NotifyEntityMove = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int id, UnityEngine.Vector3 position, UnityEngine.Vector3 vel)
		{ 
			return false;
		};
		public delegate bool NotifyPlayerCreateDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ownerHid, int entityId, UnityEngine.Vector3 createdPosition);  
		public NotifyPlayerCreateDelegate NotifyPlayerCreate = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int ownerHid, int entityId, UnityEngine.Vector3 createdPosition)
		{ 
			return false;
		};
		public delegate bool NotifyDestroyEntityDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int entityId);  
		public NotifyDestroyEntityDelegate NotifyDestroyEntity = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int entityId)
		{ 
			return false;
		};
		public delegate bool NotifyInventoryItemAddDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, GameServer.Struct.Item item);  
		public NotifyInventoryItemAddDelegate NotifyInventoryItemAdd = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, GameServer.Struct.Item item)
		{ 
			return false;
		};
		public delegate bool GivePlayerItemDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, HostID PlayerHostID);  
		public GivePlayerItemDelegate GivePlayerItem = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, HostID PlayerHostID)
		{ 
			return false;
		};
		public delegate bool NotifyPlayerItemUseDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int targetId, int itemEntityId);  
		public NotifyPlayerItemUseDelegate NotifyPlayerItemUse = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int targetId, int itemEntityId)
		{ 
			return false;
		};
		public delegate bool NotifyEntityBuffAddDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int entityId, int buffIndex);  
		public NotifyEntityBuffAddDelegate NotifyEntityBuffAdd = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int entityId, int buffIndex)
		{ 
			return false;
		};
	public override bool ProcessReceivedMessage(Nettention.Proud.ReceivedMessage pa, Object hostTag) 
	{
		Nettention.Proud.HostID remote=pa.RemoteHostID;
		if(remote==Nettention.Proud.HostID.HostID_None)
		{
			ShowUnknownHostIDWarning(remote);
		}

		Nettention.Proud.Message __msg=pa.ReadOnlyMessage;
		int orgReadOffset = __msg.ReadOffset;
        Nettention.Proud.RmiID __rmiID = Nettention.Proud.RmiID.RmiID_None;
        if (!__msg.Read( out __rmiID))
            goto __fail;
					
		switch(__rmiID)
		{
        case Common.SendTest:
            ProcessReceivedMessage_SendTest(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyJoinPlayer:
            ProcessReceivedMessage_NotifyJoinPlayer(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyLeavePlayeR:
            ProcessReceivedMessage_NotifyLeavePlayeR(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyServerMessage:
            ProcessReceivedMessage_NotifyServerMessage(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyItemCreate:
            ProcessReceivedMessage_NotifyItemCreate(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyEntityMove:
            ProcessReceivedMessage_NotifyEntityMove(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyPlayerCreate:
            ProcessReceivedMessage_NotifyPlayerCreate(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyDestroyEntity:
            ProcessReceivedMessage_NotifyDestroyEntity(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyInventoryItemAdd:
            ProcessReceivedMessage_NotifyInventoryItemAdd(__msg, pa, hostTag, remote);
            break;
        case Common.GivePlayerItem:
            ProcessReceivedMessage_GivePlayerItem(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyPlayerItemUse:
            ProcessReceivedMessage_NotifyPlayerItemUse(__msg, pa, hostTag, remote);
            break;
        case Common.NotifyEntityBuffAdd:
            ProcessReceivedMessage_NotifyEntityBuffAdd(__msg, pa, hostTag, remote);
            break;
		default:
			 goto __fail;
		}
		return true;
__fail:
	  {
			__msg.ReadOffset = orgReadOffset;
			return false;
	  }
	}
    void ProcessReceivedMessage_SendTest(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        string value; MyMarshaler.Read(__msg,out value);	
core.PostCheckReadMessage(__msg, RmiName_SendTest);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=value.ToString()+",";
        NotifyCallFromStub(Common.SendTest, RmiName_SendTest,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.SendTest;
        summary.rmiName = RmiName_SendTest;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =SendTest (remote,ctx , value );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_SendTest);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.SendTest;
        summary.rmiName = RmiName_SendTest;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyJoinPlayer(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        GameServer.Struct.NEntityList joinedPlayers; MyMarshaler.Read(__msg,out joinedPlayers);	
core.PostCheckReadMessage(__msg, RmiName_NotifyJoinPlayer);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=joinedPlayers.ToString()+",";
        NotifyCallFromStub(Common.NotifyJoinPlayer, RmiName_NotifyJoinPlayer,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyJoinPlayer;
        summary.rmiName = RmiName_NotifyJoinPlayer;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyJoinPlayer (remote,ctx , joinedPlayers );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyJoinPlayer);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyJoinPlayer;
        summary.rmiName = RmiName_NotifyJoinPlayer;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyLeavePlayeR(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int playerHostId; MyMarshaler.Read(__msg,out playerHostId);	
core.PostCheckReadMessage(__msg, RmiName_NotifyLeavePlayeR);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=playerHostId.ToString()+",";
        NotifyCallFromStub(Common.NotifyLeavePlayeR, RmiName_NotifyLeavePlayeR,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyLeavePlayeR;
        summary.rmiName = RmiName_NotifyLeavePlayeR;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyLeavePlayeR (remote,ctx , playerHostId );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyLeavePlayeR);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyLeavePlayeR;
        summary.rmiName = RmiName_NotifyLeavePlayeR;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyServerMessage(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        string msg; MyMarshaler.Read(__msg,out msg);	
core.PostCheckReadMessage(__msg, RmiName_NotifyServerMessage);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=msg.ToString()+",";
        NotifyCallFromStub(Common.NotifyServerMessage, RmiName_NotifyServerMessage,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyServerMessage;
        summary.rmiName = RmiName_NotifyServerMessage;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyServerMessage (remote,ctx , msg );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyServerMessage);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyServerMessage;
        summary.rmiName = RmiName_NotifyServerMessage;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyItemCreate(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int id; MyMarshaler.Read(__msg,out id);	
int itemIndex; MyMarshaler.Read(__msg,out itemIndex);	
UnityEngine.Vector3 createdPosition; MyMarshaler.Read(__msg,out createdPosition);	
core.PostCheckReadMessage(__msg, RmiName_NotifyItemCreate);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=id.ToString()+",";
parameterString+=itemIndex.ToString()+",";
parameterString+=createdPosition.ToString()+",";
        NotifyCallFromStub(Common.NotifyItemCreate, RmiName_NotifyItemCreate,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyItemCreate;
        summary.rmiName = RmiName_NotifyItemCreate;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyItemCreate (remote,ctx , id, itemIndex, createdPosition );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyItemCreate);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyItemCreate;
        summary.rmiName = RmiName_NotifyItemCreate;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyEntityMove(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int id; MyMarshaler.Read(__msg,out id);	
UnityEngine.Vector3 position; MyMarshaler.Read(__msg,out position);	
UnityEngine.Vector3 vel; MyMarshaler.Read(__msg,out vel);	
core.PostCheckReadMessage(__msg, RmiName_NotifyEntityMove);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=id.ToString()+",";
parameterString+=position.ToString()+",";
parameterString+=vel.ToString()+",";
        NotifyCallFromStub(Common.NotifyEntityMove, RmiName_NotifyEntityMove,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyEntityMove;
        summary.rmiName = RmiName_NotifyEntityMove;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyEntityMove (remote,ctx , id, position, vel );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyEntityMove);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyEntityMove;
        summary.rmiName = RmiName_NotifyEntityMove;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyPlayerCreate(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int ownerHid; MyMarshaler.Read(__msg,out ownerHid);	
int entityId; MyMarshaler.Read(__msg,out entityId);	
UnityEngine.Vector3 createdPosition; MyMarshaler.Read(__msg,out createdPosition);	
core.PostCheckReadMessage(__msg, RmiName_NotifyPlayerCreate);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=ownerHid.ToString()+",";
parameterString+=entityId.ToString()+",";
parameterString+=createdPosition.ToString()+",";
        NotifyCallFromStub(Common.NotifyPlayerCreate, RmiName_NotifyPlayerCreate,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyPlayerCreate;
        summary.rmiName = RmiName_NotifyPlayerCreate;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyPlayerCreate (remote,ctx , ownerHid, entityId, createdPosition );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyPlayerCreate);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyPlayerCreate;
        summary.rmiName = RmiName_NotifyPlayerCreate;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyDestroyEntity(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int entityId; MyMarshaler.Read(__msg,out entityId);	
core.PostCheckReadMessage(__msg, RmiName_NotifyDestroyEntity);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=entityId.ToString()+",";
        NotifyCallFromStub(Common.NotifyDestroyEntity, RmiName_NotifyDestroyEntity,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyDestroyEntity;
        summary.rmiName = RmiName_NotifyDestroyEntity;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyDestroyEntity (remote,ctx , entityId );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyDestroyEntity);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyDestroyEntity;
        summary.rmiName = RmiName_NotifyDestroyEntity;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyInventoryItemAdd(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        GameServer.Struct.Item item; MyMarshaler.Read(__msg,out item);	
core.PostCheckReadMessage(__msg, RmiName_NotifyInventoryItemAdd);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=item.ToString()+",";
        NotifyCallFromStub(Common.NotifyInventoryItemAdd, RmiName_NotifyInventoryItemAdd,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyInventoryItemAdd;
        summary.rmiName = RmiName_NotifyInventoryItemAdd;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyInventoryItemAdd (remote,ctx , item );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyInventoryItemAdd);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyInventoryItemAdd;
        summary.rmiName = RmiName_NotifyInventoryItemAdd;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_GivePlayerItem(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        HostID PlayerHostID; MyMarshaler.Read(__msg,out PlayerHostID);	
core.PostCheckReadMessage(__msg, RmiName_GivePlayerItem);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=PlayerHostID.ToString()+",";
        NotifyCallFromStub(Common.GivePlayerItem, RmiName_GivePlayerItem,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.GivePlayerItem;
        summary.rmiName = RmiName_GivePlayerItem;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =GivePlayerItem (remote,ctx , PlayerHostID );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_GivePlayerItem);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.GivePlayerItem;
        summary.rmiName = RmiName_GivePlayerItem;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyPlayerItemUse(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int targetId; MyMarshaler.Read(__msg,out targetId);	
int itemEntityId; MyMarshaler.Read(__msg,out itemEntityId);	
core.PostCheckReadMessage(__msg, RmiName_NotifyPlayerItemUse);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=targetId.ToString()+",";
parameterString+=itemEntityId.ToString()+",";
        NotifyCallFromStub(Common.NotifyPlayerItemUse, RmiName_NotifyPlayerItemUse,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyPlayerItemUse;
        summary.rmiName = RmiName_NotifyPlayerItemUse;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyPlayerItemUse (remote,ctx , targetId, itemEntityId );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyPlayerItemUse);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyPlayerItemUse;
        summary.rmiName = RmiName_NotifyPlayerItemUse;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
    void ProcessReceivedMessage_NotifyEntityBuffAdd(Nettention.Proud.Message __msg, Nettention.Proud.ReceivedMessage pa, Object hostTag, Nettention.Proud.HostID remote)
    {
        Nettention.Proud.RmiContext ctx = new Nettention.Proud.RmiContext();
        ctx.sentFrom=pa.RemoteHostID;
        ctx.relayed=pa.IsRelayed;
        ctx.hostTag=hostTag;
        ctx.encryptMode = pa.EncryptMode;
        ctx.compressMode = pa.CompressMode;

        int entityId; MyMarshaler.Read(__msg,out entityId);	
int buffIndex; MyMarshaler.Read(__msg,out buffIndex);	
core.PostCheckReadMessage(__msg, RmiName_NotifyEntityBuffAdd);
        if(enableNotifyCallFromStub==true)
        {
        string parameterString = "";
        parameterString+=entityId.ToString()+",";
parameterString+=buffIndex.ToString()+",";
        NotifyCallFromStub(Common.NotifyEntityBuffAdd, RmiName_NotifyEntityBuffAdd,parameterString);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
        summary.rmiID = Common.NotifyEntityBuffAdd;
        summary.rmiName = RmiName_NotifyEntityBuffAdd;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        BeforeRmiInvocation(summary);
        }

        long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();

        // Call this method.
        bool __ret =NotifyEntityBuffAdd (remote,ctx , entityId, buffIndex );

        if(__ret==false)
        {
        // Error: RMI function that a user did not create has been called. 
        core.ShowNotImplementedRmiWarning(RmiName_NotifyEntityBuffAdd);
        }

        if(enableStubProfiling)
        {
        Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
        summary.rmiID = Common.NotifyEntityBuffAdd;
        summary.rmiName = RmiName_NotifyEntityBuffAdd;
        summary.hostID = remote;
        summary.hostTag = hostTag;
        summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
        AfterRmiInvocation(summary);
        }
    }
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_SendTest="SendTest";
public const string RmiName_NotifyJoinPlayer="NotifyJoinPlayer";
public const string RmiName_NotifyLeavePlayeR="NotifyLeavePlayeR";
public const string RmiName_NotifyServerMessage="NotifyServerMessage";
public const string RmiName_NotifyItemCreate="NotifyItemCreate";
public const string RmiName_NotifyEntityMove="NotifyEntityMove";
public const string RmiName_NotifyPlayerCreate="NotifyPlayerCreate";
public const string RmiName_NotifyDestroyEntity="NotifyDestroyEntity";
public const string RmiName_NotifyInventoryItemAdd="NotifyInventoryItemAdd";
public const string RmiName_GivePlayerItem="GivePlayerItem";
public const string RmiName_NotifyPlayerItemUse="NotifyPlayerItemUse";
public const string RmiName_NotifyEntityBuffAdd="NotifyEntityBuffAdd";
       
public const string RmiName_First = RmiName_SendTest;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_SendTest="";
public const string RmiName_NotifyJoinPlayer="";
public const string RmiName_NotifyLeavePlayeR="";
public const string RmiName_NotifyServerMessage="";
public const string RmiName_NotifyItemCreate="";
public const string RmiName_NotifyEntityMove="";
public const string RmiName_NotifyPlayerCreate="";
public const string RmiName_NotifyDestroyEntity="";
public const string RmiName_NotifyInventoryItemAdd="";
public const string RmiName_GivePlayerItem="";
public const string RmiName_NotifyPlayerItemUse="";
public const string RmiName_NotifyEntityBuffAdd="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList { get{return Common.RmiIDList;} }
		
	}
}

