 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
            
using Nettention.Proud; 
            
using System.Collections.Generic; 
namespace Game.Network.S2C
{
	public class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID SendTest = (Nettention.Proud.RmiID)3000+1;
			public const Nettention.Proud.RmiID NotifyJoinPlayer = (Nettention.Proud.RmiID)3000+2;
			public const Nettention.Proud.RmiID NotifyLeavePlayeR = (Nettention.Proud.RmiID)3000+3;
			public const Nettention.Proud.RmiID NotifyServerMessage = (Nettention.Proud.RmiID)3000+4;
			public const Nettention.Proud.RmiID NotifyItemCreate = (Nettention.Proud.RmiID)3000+5;
			public const Nettention.Proud.RmiID NotifyEntityMove = (Nettention.Proud.RmiID)3000+6;
			public const Nettention.Proud.RmiID NotifyPlayerCreate = (Nettention.Proud.RmiID)3000+7;
			public const Nettention.Proud.RmiID NotifyNPCList = (Nettention.Proud.RmiID)3000+8;
			public const Nettention.Proud.RmiID NotifyNPCCreate = (Nettention.Proud.RmiID)3000+9;
			public const Nettention.Proud.RmiID NotifyDestroyEntity = (Nettention.Proud.RmiID)3000+10;
			public const Nettention.Proud.RmiID NotifyInventoryItemAdd = (Nettention.Proud.RmiID)3000+11;
			public const Nettention.Proud.RmiID GivePlayerItem = (Nettention.Proud.RmiID)3000+12;
			public const Nettention.Proud.RmiID NotifyPlayerItemUse = (Nettention.Proud.RmiID)3000+13;
			public const Nettention.Proud.RmiID NotifyEntityBuffAdd = (Nettention.Proud.RmiID)3000+14;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			SendTest,
			NotifyJoinPlayer,
			NotifyLeavePlayeR,
			NotifyServerMessage,
			NotifyItemCreate,
			NotifyEntityMove,
			NotifyPlayerCreate,
			NotifyNPCList,
			NotifyNPCCreate,
			NotifyDestroyEntity,
			NotifyInventoryItemAdd,
			GivePlayerItem,
			NotifyPlayerItemUse,
			NotifyEntityBuffAdd,
		};
	}
}

				 
