




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;

            
using Nettention.Proud; 
namespace Game.Network.S2C
{
	public class Proxy:Nettention.Proud.RmiProxy
	{
public bool SendTest(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, string value)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.SendTest;
		__msg.Write(__msgid);
		MyMarshaler.Write(__msg, value);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_SendTest, Common.SendTest);
}

public bool SendTest(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, string value)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.SendTest;
__msg.Write(__msgid);
MyMarshaler.Write(__msg, value);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_SendTest, Common.SendTest);
}
public bool NotifyJoinPlayer(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int JoinedEntityIndex, HostID PlayerHostID)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.NotifyJoinPlayer;
		__msg.Write(__msgid);
		MyMarshaler.Write(__msg, JoinedEntityIndex);
		MyMarshaler.Write(__msg, PlayerHostID);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_NotifyJoinPlayer, Common.NotifyJoinPlayer);
}

public bool NotifyJoinPlayer(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, int JoinedEntityIndex, HostID PlayerHostID)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.NotifyJoinPlayer;
__msg.Write(__msgid);
MyMarshaler.Write(__msg, JoinedEntityIndex);
MyMarshaler.Write(__msg, PlayerHostID);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_NotifyJoinPlayer, Common.NotifyJoinPlayer);
}
public bool GivePlayerItem(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, HostID PlayerHostID)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
		__msg.SimplePacketMode = core.IsSimplePacketMode();
		Nettention.Proud.RmiID __msgid= Common.GivePlayerItem;
		__msg.Write(__msgid);
		MyMarshaler.Write(__msg, PlayerHostID);
		
	Nettention.Proud.HostID[] __list = new Nettention.Proud.HostID[1];
	__list[0] = remote;
		
	return RmiSend(__list,rmiContext,__msg,
		RmiName_GivePlayerItem, Common.GivePlayerItem);
}

public bool GivePlayerItem(Nettention.Proud.HostID[] remotes,Nettention.Proud.RmiContext rmiContext, HostID PlayerHostID)
{
	Nettention.Proud.Message __msg=new Nettention.Proud.Message();
__msg.SimplePacketMode = core.IsSimplePacketMode();
Nettention.Proud.RmiID __msgid= Common.GivePlayerItem;
__msg.Write(__msgid);
MyMarshaler.Write(__msg, PlayerHostID);
		
	return RmiSend(remotes,rmiContext,__msg,
		RmiName_GivePlayerItem, Common.GivePlayerItem);
}
#if USE_RMI_NAME_STRING
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_SendTest="SendTest";
public const string RmiName_NotifyJoinPlayer="NotifyJoinPlayer";
public const string RmiName_GivePlayerItem="GivePlayerItem";
       
public const string RmiName_First = RmiName_SendTest;
#else
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
public const string RmiName_SendTest="";
public const string RmiName_NotifyJoinPlayer="";
public const string RmiName_GivePlayerItem="";
       
public const string RmiName_First = "";
#endif
		public override Nettention.Proud.RmiID[] GetRmiIDList() { return Common.RmiIDList; } 
	}
}

